### ISSUE TITLE
dd

### ISSUE THREAD

**Issue by bkjeon1614** [ahra4012/Javascript#2]
```
version: '3.6'
    services:
      elasticsearch:
        image: 'docker.elastic.co/elasticsearch/elasticsearch:7.9.2'
        container_name: es01
        ports:
          - "9200:9200"
          - "9300:9300"
        environment:
          - node.name="es01"
          - cluster.name="es-docker-cluster"
          - bootstrap.memory_lock=true
          - discovery.type=single-node
          - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
        ulimits:
          memlock:
            soft: -1
            hard: -1
        networks:
          - elastic

      kibana:
        image: 'docker.elastic.co/kibana/kibana:7.9.2'
        container_name: kibana
        ports:
          - "5601:5601"
        environment:
          - ELASTICSEARCH_HOSTS=["http://es01:9200"]
        depends_on:
          - elasticsearch
        networks:
          - elastic

      cerebro:
        image: 'lmenezes/cerebro'
        container_name: 'cerebro'
        ports:
          - "9000:9000"
        environment:
          - "CEREBRO_PORT=9000"
          - "ELASTICSEARCH_HOST=http://es01:9200"
        networks:
          - elastic

    volumes:
      data01:
        driver: local
      data02:
        driver: local
      data03:
        driver: local

    networks:
      elastic:
        driver: bridge
```
